### ISSUE TITLE
[bug] 나의 여행 첫 진입 QA 피드백 반영

### ISSUE THREAD

**Issue by annapo99** [Nexters/JYP-iOS#156]
## 📝 todo
- [x] + 버튼 작게 들어감
- [x] 텍스트 중앙 정렬 필요
- [ ] 탭바 높임 필요
