### ISSUE TITLE
[feat] 플래너 날짜 선택 UI (종료 날짜) #2 

### ISSUE THREAD

**Issue by leeinae** [Nexters/JYP-iOS#25]
## 👀 Issue

시작 일정 / 종료 일정 이슈를 나눠서 진행합니다.

### ✅ Todo
- [ ] 일정 라벨 계산
- [x] focus에 따른 디자인 반영
- [x] textField 디자인 반영
- [x] 선택 버튼 활성화
- [x] bottomSheet clear version 대응 ....
