### ISSUE TITLE
[feat] 플래너 - 토론장 첫 진입 기능 구현 #1

### ISSUE THREAD

**Issue by annapo99** [Nexters/JYP-iOS#32]
## 👀 Issue
토론장 첫 진입 기능 구현 입니다.

### ✅ Todo
- [x] 재사용 가능한 태그 뷰 제작
- [x] 태그 바텀시트 구현
- [x] 리엑토킷 적용 하기
