### ISSUE TITLE
[feat] 여행 취향 태그 추가 기능 개발

### ISSUE THREAD

**Issue by leeinae** [Nexters/JYP-iOS#35]
## 👀 Issue

바텀시트로 태그 추가 기능 개발 

### ✅ Todo
- [x] addButton action 추가
- [x] buttomSheet에서 태그 추가 기능
- [x] text validation 추가
